name: Release

on:
  push:
    workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          # Optional version of trunk to install(eg. 'v0.19.1', 'latest')
          version: 'latest'

      - uses: Swatinem/rust-cache@v2

      - name: Build frontend
        run: trunk build --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: questionmark
          path: |
            dist/
